[tool.poetry]
name = "gqa-sql-service-package"
version = "0.1.0"
description = ""
authors = ["Terri Lee <terriL@motovate.co.za>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
langchain = "^0.0.346"
openai = ">=1.3,<2.0.0"
langchain-experimental = "^0.0.43"
pyodbc = "^5.0.1"
python-dotenv = "^1.0.0"

[tool.poetry.group.dev.dependencies]
langchain-cli = ">=0.0.15"
fastapi = "^0.104.0"
sse-starlette = "^1.6.5"

[tool.langserve]
export_module = "gqa_sql_service_package.chain"
export_attr = "chain"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"